{
 "title": "Node Info",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Active Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes/ on() node_memory_MemTotal_bytes*100 "
    }
   ]
  },
  {
   "title": "Occupied Disk Space",
   "type": "graph",
   "description": "Percentage of disk space occupied",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100-(avg(node_filesystem_avail_bytes / node_filesystem_size_bytes) *100)"
    }
   ]
  },
  {
   "title": "Visitor Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(my_page_visits_total)" }
   ]
  },
  {
   "title": "Average request process time per page",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_process_time_sum / on(endpoint) request_process_time_count"
    }
   ]
  },
  {
   "title": "CPU usage ",
   "type": "graph",
   "description": "Rate of CPU usage per second averaged across all CPU's ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (cpu)(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])))"
    }
   ]
  }
 ]
}